# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'RuNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PinLayout'
  pod 'Dip'
  pod 'RxCocoa', '5.1.0'
  pod 'RxSwift', '5.1.0'
  pod 'Kingfisher', '5.12'
  pod 'RealmSwift'

end
